# Generated by Django 5.1 on 2024-09-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_comment_user_remove_complaint_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
    ]
