# Generated by Django 5.1 on 2024-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_remove_complaint_created_at_remove_complaint_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
