# Generated by Django 5.1 on 2024-09-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user_name',
            new_name='userName',
        ),
    ]
