# Generated by Django 5.1 on 2024-09-07 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_rename_user_name_complaint_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
